### ISSUE TITLE
Support for ElementAPI

### ISSUE THREAD

**Issue by knynkwl** [benjamminf/craft-coordinates#1]
Can I use this in conjunction with the ElementAPI plugin?

for example, I'd love to export lat/long instead of a address.
`'address' => $entry->address,`

https://github.com/pixelandtonic/ElementAPI

**Comment by benjamminf** [comment]
There's a service level API you can use. The following code should cover your needs:

``` php
$coords = craft()->coordinates->getModel($entry->address);
$lat = $coords->latitude;
$lng = $coords->longitude;
```

**Comment by knynkwl** [comment]
Awesome, got it. Thanks!
